#!/bin/bash

echo "🔧 Configuração das Variáveis de Ambiente do Supabase para GitHub Pages"
echo "=================================================================="
echo ""
echo "Para corrigir o erro 'Missing Supabase environment variables', você precisa:"
echo ""
echo "1. Acessar o repositório no GitHub: https://github.com/VeigaTeam/pedidos"
echo ""
echo "2. Ir em Settings > Secrets and variables > Actions"
echo ""
echo "3. Adicionar os seguintes secrets:"
echo ""
echo "   Secret Name: VITE_SUPABASE_URL"
echo "   Secret Value: https://eglxlvzkrfjhfexipudj.supabase.co"
echo ""
echo "   Secret Name: VITE_SUPABASE_ANON_KEY"
echo "   Secret Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnbHhsdnprcmZqaGZleGlwdWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDE5OTUsImV4cCI6MjA2NzY3Nzk5NX0.NGSXF3dun82LWXlT8HdgLH_jBfhGJFH-m19y5SwiebQ"
echo ""
echo "4. Após adicionar os secrets, fazer push das mudanças do workflow:"
echo "   git add .github/workflows/deploy.yml"
echo "   git commit -m 'Add Supabase environment variables to GitHub Actions'"
echo "   git push origin main"
echo ""
echo "5. O GitHub Actions irá executar automaticamente e a página funcionará!"
echo ""
echo "⚠️  IMPORTANTE: As credenciais do Supabase são públicas (anon key),"
echo "   então é seguro incluí-las no build. A segurança é controlada pelas"
echo "   políticas RLS (Row Level Security) no Supabase."
echo ""
